### ISSUE TITLE
Check MapReduce/Broadcast output correctness

### ISSUE THREAD

**Issue by johnyangk** [snuspl/onyx#469]
Currently the integration tests only check whether jobs finish without an error.
Let's go one step further and also check the correctness of the outputs.

This should be straightforward for the MapReduce and Broadcast tests.
For ML tests, I suggest we write the updated model to a file after every iteration. We can save the expected model files in the repository and in the tests compare the output files with them.

**Comment by johnyangk** [comment]
Changed the issue to only consider MapReduce/Broadcast.
Added @skystar-p to the assignee list.

**Comment by johnyangk** [comment]
@skystar-p meeting notes
* Manually run the application to generate output files (The outputs should be correct, but please double check)
* Concatenate the outputs into a single file, sort the file and save it in `examples/src/main/resources`
* In `/tests`, create a common method for comparing outputs to the saved file
* Use the method to check MapReduce/Broadcast output correctness in the integration tests
* File a PR, and ask @seojangho and @jeongyooneo for review

**Comment by seojangho** [comment]
Blocked by #695

**Comment by wonook** [comment]
Any plans to check for validity of ALS / MLR as well?
