### ISSUE TITLE
Add publications to the website

### ISSUE THREAD

**Issue by johnyangk** [snuspl/onyx#689]
For example, [Pado(EuroSys17) ](http://spl.snu.ac.kr/wp-content/uploads/2017/11/p575-Yang.pdf)

**Comment by wonook** [comment]
Should this be shown on a separate page called 'publications'? or should we just create something like 'related works'? Please be more specific :)

**Comment by wonook** [comment]
Or would it be enough to show this in like the 'overview' page?

**Comment by johnyangk** [comment]
Closing for now, as per the discussion on Slack.
