### ISSUE TITLE
Fix all coders to finally throw IOException

### ISSUE THREAD

**Issue by skystar-p** [snuspl/onyx#702]
Currently, all coders are implementing our `Coder` interface, which throws `IOException` in its `encode()` and `decode()` methods. We can fix other coders to wrap exception to `IOException`.

**Comment by seojangho** [comment]
We need to resolve this, since we do not want to handle any Beam-specific exceptions in error-handling logic.

**Comment by wonook** [comment]
Can you check if it hasnt been already handled by #700?

**Comment by skystar-p** [comment]
@wonook No. If you run example script, sometimes it fails because `CoderException` is not handled. So we should modify `BeamCoder` to wrap `CoderException` into `IOException`.
