### ISSUE TITLE
Remote Block Metadata in File

### ISSUE THREAD

**Issue by sanha** [snuspl/onyx#715]
At now, every remote block metadata (including partition metadata) is stored in `BlockManagerMaster` which resides in driver side.
It works well now, but maintaining metadata for TB-scale intermediate data can be burdensome for driver.

For example, if we think a single shuffle for 1TB data,
- each map task process 128 MB data 
- about 8000 map tasks and 4000 reduce tasks
- 8000 * 4000 partitions
- 32 bytes metadata per partition
-> about 1 GB metadata (for a single shuffle)

If there are a lot of shuffles in a plan (e.g., ALS job), the driver will be overloaded.

Therefore, it would be good to maintain block metadata in a separate file (instead of driver side.)
Also, if we store block metadata in file, we don't need to reserve / report every partition write to master.

**Comment by johnyangk** [comment]
Sounds great!
